---
title: "Embryonic RG"
author: "Daniel J. Kunz"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: zenburn
    code_folding: hide
editor_options:
  chunk_output_type: console
---



```{r setup, message=FALSE, warning=TRUE}
library(ggplot2)
library(viridis)
library(patchwork)

library(readr)
library(dplyr)
library(tibble)
```



```{r, message=FALSE, warning=TRUE}
source("code/core_settings.R")
source("code/core_functions.R")
```


```{r}
# set parameters
fileID = "normal_subset_embryonic_RG_cleaned"
leiden_res = 'leiden_0_33'
leiden_res_annot = 'annot_leiden_0_33'

adata_path = paste0('data/forebrain_', fileID, '.h5ad')
```


```{r}
#repl_python()
py_run_string("import numpy as np")
py_run_string("import anndata as ad")

py_run_string("adata = ad.read_h5ad(r.adata_path)")
```


```{r, message=FALSE, warning=TRUE}
metadata_scanpy = as_tibble(py$adata$obs, rownames="cellID") %>%
                    rename(mt_frac = percent_mito) %>%
                    mutate(UMAP_dim1 = py$adata$obsm[['X_umap']][,1],
                           UMAP_dim2 = py$adata$obsm[['X_umap']][,2])

metadata_experiment = read_tsv("data/metadata_experiment.tsv")
results_cyclone = read_csv("data/cyclone/cyclone_merged.csv.gz", col_types="ccddd") %>%
                    mutate(sampleID = sapply(cellID, function(cell) strsplit(cell, split="-")[[1]][3])) %>%
                    left_join(metadata_experiment, by="sampleID") %>%
                    mutate(cellID = gsub("-1", "", cellID)) %>%
                    select(cellID, cyclone, cyclone_G1, cyclone_S, cyclone_G2M)

results_logreg = read_csv(paste0("data/logreg/logreg_Zeisel_2018_normal.csv.gz"))



# filter QC
metadata = left_join(metadata_scanpy, results_cyclone, by="cellID") %>%
              mutate(cyclone = factor(cyclone, levels=c("G1", "S", "G2M"))) %>%
              mutate(timepoint = factor(timepoint, levels=unique(timepoint)[order(unique(postnatal_day))])) %>%
              left_join(results_logreg, by="cellID") %>%
              mutate(leiden = get(leiden_res))  %>%
              mutate(gate_gfp = gsub("SOX2_-ve", "GFP-", gate)) %>%
              mutate(gate_gfp = gsub("SOX2_\\+ve", "GFP+ [SOX2]", gate_gfp))
              
              
# metadata_export = metadata %>% select(cellID, sampleID, tissue, gate, timepoint,
#                                       postnatal_day, set, treatment, condition, n_genes,
#                                       mt_frac, n_counts, leiden_0_33, annot_leiden_0_33,
#                                       leiden, annot_leiden, UMAP_dim1, UMAP_dim2,
#                                       cyclone, cyclone_G1, cyclone_S, cyclone_G2M,
#                                       prediction_Class, probability_Class,
#                                       prediction_TaxonomyRank1, probability_TaxonomyRank1,
#                                       gate_gfp)
# 
# 
# write_csv(metadata_export, "data/metadata_embryonic_RG_2020-11-18.csv")

# tbl_hvg = tibble(external_gene_name = py$adata$var_names$values,
#                  ensembl_gene_id = py$adata$var$gene_ids)
# 
# write_csv(tbl_hvg, "data/HVG_embryonic_RG_2020-11-18.csv.gz")
```

# Samples

```{r, fig.asp=0.3, message=FALSE, warning=TRUE}
sample_counts = metadata %>%
                  group_by(timepoint, gate_gfp) %>%
                  summarise(n_cells= n())

plt_bar_samples = ggplot(sample_counts, aes(x=timepoint, y=n_cells, fill=gate_gfp)) +
                            geom_bar(stat="identity", position="dodge") +
                            # scale_colour_viridis() +
                            # scale_fill_manual(values=c("SOX2_-ve"="#1F77B4", "SOX2_+ve"="#FF7F0E")) +
                            scale_fill_manual(values=c("GFP-"="#CCCCCC", "GFP+ [SOX2]"="#65A83E")) +
                            theme_publication +
                            labs(x="Timepoint", y="Number of Cells") +
                            labs(fill="FACS Gate") +
                            guides(colour = guide_legend(override.aes = list(size=2)))

plt_bar_samples
```



# Timepoints


```{r}
colour_map = c("E12.5"="#fdcc8a",
              "E14.5"="#fc8d59",
              "E16.5"="#d7301f",
              "P0"="#bdc9e1",
              "P2"="#74a9cf",
              "P7"="#0570b0",
              "P13"="#d9d9d9",
              "P19"="#bdbdbd",
              "P39"="#969696",
              "P111"="#636363",
              "P365"="#252525")

library(ggrastr)
                            
plt_UMAP_day = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, colour=timepoint)) +
                            geom_point(size=0.05, alpha=0.8, shape=16) +
                            # geom_point_rast(size=0.05, alpha=0.8, shape=16, raster.dpi=300) +
                            # scale_colour_viridis(discrete=T) +
                            scale_color_manual(values=colour_map) +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(colour="Time point") +
                            guides(colour = guide_legend(override.aes = list(size=2),
                                                         keyheight=0.3,
                                                         default.unit="cm"))
```

```{r}
plt_UMAP_day
```



# Cell Type Mapping

Map cell annotation from Zeisel 2018 using logistic regression.

```{r, fig.asp=0.3}
plt_UMAP_logreg = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, colour=prediction_TaxonomyRank1)) +
                            geom_point(size=0.2, alpha=0.6, shape=16) +
                            # scale_colour_viridis() +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(colour="Logreg") +
                            guides(colour = guide_legend(override.aes = list(size=2)))


plt_UMAP_logreg_prob = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, colour=probability_TaxonomyRank1)) +
                            geom_point(size=0.2, alpha=0.6, shape=16) +
                            scale_colour_viridis() +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(colour="Logreg Probability")

plt_UMAP_logreg | plt_UMAP_logreg_prob
```




# Sox2 Gate

```{r, fig.asp=0.3}
# randomise order for plot
plt_UMAP_gate = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, colour=gate_gfp)) +
                            geom_point(size=0.5, alpha=0.6, shape=16) +
                            # scale_color_manual(values=c("SOX2_-ve"="#1F77B4", "SOX2_+ve"="#FF7F0E", "tdTomato_-ve"="black", "tdTomato_+ve"="red")) +
                            scale_colour_manual(values=c("GFP-"="#CCCCCC", "GFP+ [SOX2]"="#65A83E")) +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(colour="FACS Gate") +
                            guides(colour = guide_legend(override.aes = list(size=2)))


panel_Sox2 = plt_UMAP_gate | plot_UMAP_expr("Sox2")

panel_Sox2
```

# Cell Cycle

```{r, fig.asp=0.3}
panel_ccgenes = plot_UMAP_expr("Mki67") | plot_UMAP_expr("Top2a")

panel_ccgenes
```

```{r}
expr_cellcycle = get_adata_raw_expr(c("Mki67", "Top2a"))


metadata_cc = metadata %>%
            left_join(expr_cellcycle, by="cellID") %>%
            mutate(cell_cycle = if_else(expr_Mki67 > 1 | expr_Top2a > 1, as.vector(cyclone), "G0")) %>%
            mutate(cell_cycle = factor(cell_cycle, levels=c("G0", "G1", "S", "G2M"))) %>%
            arrange(cell_cycle) %>%
            slice(c(1:sum(cell_cycle == "G0"), sample((sum(cell_cycle == "G0") + 1):n())))
```

```{r}
plt_panel_UMAP_cellcycle = ggplot(metadata_cc, aes(x=UMAP_dim1, y=UMAP_dim2, colour=cell_cycle)) +
                            # geom_point_rast(size=0.1, alpha=0.8, shape=16, raster.dpi=600) +
                            geom_point(size=0.1, alpha=0.8, shape=16) +
                            scale_color_manual(values=c("G0"="#D0DFE6", "G1"="#19476F", "S"="#E47E00", "G2M"="#90353B")) +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(colour="Cell cycle") +
                            # labs(title=NULL) +
                            guides(colour = guide_legend(override.aes = list(size=2),
                                                         keyheight=0.3,
                                                         default.unit="cm"))
```

```{r}
plt_panel_UMAP_cellcycle
```


# Cell Stats

```{r, fig.asp=0.6}
plt_UMAP_n_counts = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, z=n_counts)) +
                            stat_summary_hex(bins=100) +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(fill="Counts")

plt_UMAP_n_genes = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, z=n_genes)) +
                            stat_summary_hex(bins=100) +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(fill="Genes")

plt_UMAP_mt = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, z=mt_frac)) +
                            stat_summary_hex(bins=100) +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            labs(x="UMAP 1", y="UMAP 2") +
                            theme(axis.text.x=element_blank(),
                                  axis.ticks.x=element_blank(),
                                  axis.text.y=element_blank(),
                                  axis.ticks.y=element_blank()) +
                            labs(fill="MT Content")


plt_UMAP_n_counts + plt_UMAP_n_genes + plt_UMAP_mt + plot_layout(ncol=2)
```


# Annotation

```{r}
plot_UMAP_leiden("annot_leiden")
```


# Marker Genes

```{r, fig.asp=0.3}
plot_UMAP_expr("Sox2") + plot_UMAP_expr("Nes")
plot_UMAP_expr("Hes1") + plot_UMAP_expr("Prom1")
plot_UMAP_expr("Aldoc") + plot_UMAP_expr("Slc1a3")
plot_UMAP_expr("Vcam1") + plot_UMAP_expr("Ntsr2")
plot_UMAP_expr("Aqp4") + plot_UMAP_expr("Gja1")
plot_UMAP_expr("Nhlh2") + plot_UMAP_expr("Nhlh1")
plot_UMAP_expr("Ebf2") + plot_UMAP_expr("Ebf1")
plot_UMAP_expr("Reln") + plot_UMAP_expr("Mki67")
plot_UMAP_expr("Dcx") + plot_UMAP_expr("Dlx1")
plot_UMAP_expr("Dlx2") + plot_UMAP_expr("Dlx5")
plot_UMAP_expr("Sp9") + plot_UMAP_expr("Neurod2")
plot_UMAP_expr("Tbr1") + plot_UMAP_expr("Olig2")
plot_UMAP_expr("Olig1") + plot_UMAP_expr("Pdgfra")
plot_UMAP_expr("Fyn") + plot_UMAP_expr("Plp1")
plot_UMAP_expr("Mbp") + plot_UMAP_expr("Foxj1")
plot_UMAP_expr("Gad2") + plot_UMAP_expr("Gata2")
plot_UMAP_expr("Gata3") + plot_UMAP_expr("Rarb")
plot_UMAP_expr("Col1a1") + plot_UMAP_expr("Col1a2")
plot_UMAP_expr("Csf1r") + plot_UMAP_expr("P2ry12")
plot_UMAP_expr("Tmem119") + plot_UMAP_expr("Cd14")
plot_UMAP_expr("Mrc1") + plot_UMAP_expr("Lyve1")
plot_UMAP_expr("Cd3e") + plot_UMAP_expr("Trbc1")
plot_UMAP_expr("Alas2") + plot_UMAP_expr("Hbb-bt")
plot_UMAP_expr("Ttr") + plot_UMAP_expr("Flt1")
plot_UMAP_expr("S100a8") + plot_UMAP_expr("S100a9")
```





# DE gene plots

## Top 30 based on q-value ranking

```{r}
file_paths_DE = list.files(path=paste0("output/", fileID, "/DE-voom_limma/"), pattern="DE-voom_limma_normal_subset_embryonic_RG_cleaned_DE_leiden_0_33*", full.names=T)


top_DE = c()

for (file_path in file_paths_DE){
  top_DE_cluster = read_csv(file_path, col_types="cddddddd") %>%
                          arrange(qval, log2fc) %>%
                          filter(qval < 0.05) %>%
                          filter(log2fc < 0) %>%
                          slice(1:30) %>%
                          pull(geneID)
  top_DE = c(top_DE, top_DE_cluster)
}

top_DE = top_DE %>% unique()
```

```{r, message=FALSE, warning=TRUE}
marker_list = top_DE

tbl_markers = get_adata_raw_expr(marker_list) %>%
                left_join(metadata %>% select(!!(leiden_res_annot), cellID), by="cellID") %>%
                rename("leiden_res_annot" = !!(leiden_res_annot)) %>%
                select(-cellID)


tbl_markers_melt = as_tibble(melt(tbl_markers, id.vars="leiden_res_annot", value.name="expr", variable.name='geneID')) %>%
                      mutate(geneID = gsub("^expr_", "", geneID)) %>%
                      mutate(geneID = gsub("Nkx2_1", "Nkx2-1", geneID)) %>%
                      filter(geneID %in% marker_list)

tbl_markers_average = tbl_markers_melt %>%
                        group_by(geneID, leiden_res_annot) %>%
                        # mutate(expr = (expr - min(expr))/(max(expr) - min(expr))) %>%
                        summarise(mean_expr = mean(expr),
                                  fraction_expressed = sum(expr > 0)/n()) %>%
                        group_by(geneID) %>%
                        mutate(mean_expr = mean_expr/max(mean_expr)) %>%
                        ungroup()

tbl_markers_sub = tbl_markers_average %>% select(-fraction_expressed)

data_wide = tidyr::spread(tbl_markers_sub, leiden_res_annot, mean_expr)
cmat = data_wide %>% ungroup() %>% select(-geneID) %>% as.matrix()
rownames(cmat) = as.vector(data_wide$geneID)
```

```{r, message=FALSE, warning=TRUE}
tbl_markers_average = tbl_markers_average %>%
                       #  mutate(leiden_res_annot = factor(leiden_res_annot, levels = annot_order)) %>%
                       # mutate(leiden_res_annot = factor(leiden_res_annot, levels=c("Embryonic RG", "Juvenile RG", "Active NSCs", "Quiescent NSCs [1]", "Quiescent NSCs [2]"))) %>%
                        # mutate(geneID = factor(geneID, levels =rownames(cmat)[mat_cluster_rows$order]))
                        mutate(geneID = factor(geneID, levels=marker_list))


library("RColorBrewer")

plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=geneID, y=leiden_res_annot, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
```

```{r, fig.asp=0.25}
plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```


```{r, fig.asp=2.2}
plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=leiden_res_annot, y=geneID, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))


plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```


## Top 30 based on cluster LFC

```{r}
file_paths_DE = list.files(path=paste0("output/", fileID, "/DE-voom_limma/"), pattern="DE-voom_limma_normal_subset_embryonic_RG_cleaned_DE_leiden_0_33*", full.names=T)


top_DE = c()

for (file_path in file_paths_DE){
  top_DE_cluster = read_csv(file_path, col_types="cddddddd") %>%
                          filter(qval < 0.05) %>%
                          filter(log2fc < 0) %>%
                          arrange(cluster_LFC) %>%
                          slice(1:30) %>%
                          pull(geneID)
  top_DE = c(top_DE, top_DE_cluster)
}

top_DE = top_DE %>% unique()
```

```{r, message=FALSE, warning=TRUE}
marker_list = top_DE

tbl_markers = get_adata_raw_expr(marker_list) %>%
                left_join(metadata %>% select(!!(leiden_res_annot), cellID), by="cellID") %>%
                rename("leiden_res_annot" = !!(leiden_res_annot)) %>%
                select(-cellID)


tbl_markers_melt = as_tibble(melt(tbl_markers, id.vars="leiden_res_annot", value.name="expr", variable.name='geneID')) %>%
                      mutate(geneID = gsub("^expr_", "", geneID)) %>%
                      mutate(geneID = gsub("Nkx2_1", "Nkx2-1", geneID)) %>%
                      filter(geneID %in% marker_list)

tbl_markers_average = tbl_markers_melt %>%
                        group_by(geneID, leiden_res_annot) %>%
                        # mutate(expr = (expr - min(expr))/(max(expr) - min(expr))) %>%
                        summarise(mean_expr = mean(expr),
                                  fraction_expressed = sum(expr > 0)/n()) %>%
                        group_by(geneID) %>%
                        mutate(mean_expr = mean_expr/max(mean_expr)) %>%
                        ungroup()

tbl_markers_sub = tbl_markers_average %>% select(-fraction_expressed)

data_wide = tidyr::spread(tbl_markers_sub, leiden_res_annot, mean_expr)
cmat = data_wide %>% ungroup() %>% select(-geneID) %>% as.matrix()
rownames(cmat) = as.vector(data_wide$geneID)
```

```{r, message=FALSE, warning=TRUE}
tbl_markers_average = tbl_markers_average %>%
                       #  mutate(leiden_res_annot = factor(leiden_res_annot, levels = annot_order)) %>%
                       # mutate(leiden_res_annot = factor(leiden_res_annot, levels=c("Embryonic RG", "Juvenile RG", "Active NSCs", "Quiescent NSCs [1]", "Quiescent NSCs [2]"))) %>%
                        # mutate(geneID = factor(geneID, levels =rownames(cmat)[mat_cluster_rows$order]))
                        mutate(geneID = factor(geneID, levels=marker_list))


library("RColorBrewer")

plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=geneID, y=leiden_res_annot, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))
```

```{r, fig.asp=0.25}
plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```


```{r, fig.asp=2.2}
plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=leiden_res_annot, y=geneID, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))


plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```


```{r}
file_paths_DE = list.files(path=paste0("output/", fileID, "/DE-voom_limma/"), pattern="DE-voom_limma_normal_subset_embryonic_RG_cleaned_DE_leiden_0_33*", full.names=T)


top_DE = c()

for (file_path in file_paths_DE){
  top_DE_cluster = read_csv(file_path, col_types="cddddddd") %>%
                          filter(qval < 0.05) %>%
                          filter(log2fc < 0) %>%
                          arrange(cluster_LFC) %>%
                          slice(1:10) %>%
                          pull(geneID)
  top_DE = c(top_DE, top_DE_cluster)
}

top_DE = top_DE %>% unique()
```

```{r, message=FALSE, warning=TRUE}
marker_list = top_DE

tbl_markers = get_adata_raw_expr(marker_list) %>%
                left_join(metadata %>% select(!!(leiden_res_annot), cellID), by="cellID") %>%
                rename("leiden_res_annot" = !!(leiden_res_annot)) %>%
                select(-cellID)


tbl_markers_melt = as_tibble(melt(tbl_markers, id.vars="leiden_res_annot", value.name="expr", variable.name='geneID')) %>%
                      mutate(geneID = gsub("^expr_", "", geneID)) %>%
                      mutate(geneID = gsub("Nkx2_1", "Nkx2-1", geneID)) %>%
                      filter(geneID %in% marker_list)

tbl_markers_average = tbl_markers_melt %>%
                        group_by(geneID, leiden_res_annot) %>%
                        # mutate(expr = (expr - min(expr))/(max(expr) - min(expr))) %>%
                        summarise(mean_expr = mean(expr),
                                  fraction_expressed = sum(expr > 0)/n()) %>%
                        group_by(geneID) %>%
                        mutate(mean_expr = mean_expr/max(mean_expr)) %>%
                        ungroup()

tbl_markers_sub = tbl_markers_average %>% select(-fraction_expressed)

data_wide = tidyr::spread(tbl_markers_sub, leiden_res_annot, mean_expr)
cmat = data_wide %>% ungroup() %>% select(-geneID) %>% as.matrix()
rownames(cmat) = as.vector(data_wide$geneID)
```

```{r, message=FALSE, warning=TRUE}
tbl_markers_average = tbl_markers_average %>%
                       #  mutate(leiden_res_annot = factor(leiden_res_annot, levels = annot_order)) %>%
                       # mutate(leiden_res_annot = factor(leiden_res_annot, levels=c("Embryonic RG", "Juvenile RG", "Active NSCs", "Quiescent NSCs [1]", "Quiescent NSCs [2]"))) %>%
                        # mutate(geneID = factor(geneID, levels =rownames(cmat)[mat_cluster_rows$order]))
                        mutate(geneID = factor(geneID, levels=marker_list))


library("RColorBrewer")

plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=geneID, y=leiden_res_annot, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))
```

```{r, fig.asp=0.25}
plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```


```{r, fig.asp=2.2}
plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=leiden_res_annot, y=geneID, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))


plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```




## Top 30 TF based on q-value ranking

```{r}
top_DE_TF = c()
list_TF = read_tsv("data/gene-groups/Mus_musculus_TF.txt") %>% pull(Symbol)


for (file_path in file_paths_DE){
  top_DE_TF_cluster = read_csv(file_path, col_types="cddddddd") %>%
                          arrange(qval, log2fc) %>%
                          filter(qval < 0.05) %>%
                          filter(log2fc < 0) %>%
                          filter(geneID %in% list_TF) %>%
                          slice(1:30) %>%
                          pull(geneID)
  top_DE_TF = c(top_DE_TF, top_DE_TF_cluster)
}

top_DE_TF = top_DE_TF %>% unique()
```

```{r, message=FALSE, warning=TRUE}
marker_list = top_DE_TF

tbl_markers = get_adata_raw_expr(marker_list) %>%
                left_join(metadata %>% select(!!(leiden_res_annot), cellID), by="cellID") %>%
                rename("leiden_res_annot" = !!(leiden_res_annot)) %>%
                select(-cellID)


tbl_markers_melt = as_tibble(melt(tbl_markers, id.vars="leiden_res_annot", value.name="expr", variable.name='geneID')) %>%
                      mutate(geneID = gsub("^expr_", "", geneID)) %>%
                      mutate(geneID = gsub("Nkx2_1", "Nkx2-1", geneID)) %>%
                      filter(geneID %in% marker_list)

tbl_markers_average = tbl_markers_melt %>%
                        group_by(geneID, leiden_res_annot) %>%
                        # mutate(expr = (expr - min(expr))/(max(expr) - min(expr))) %>%
                        summarise(mean_expr = mean(expr),
                                  fraction_expressed = sum(expr > 0)/n()) %>%
                        group_by(geneID) %>%
                        mutate(mean_expr = mean_expr/max(mean_expr)) %>%
                        ungroup()

tbl_markers_sub = tbl_markers_average %>% select(-fraction_expressed)

data_wide = tidyr::spread(tbl_markers_sub, leiden_res_annot, mean_expr)
cmat = data_wide %>% ungroup() %>% select(-geneID) %>% as.matrix()
rownames(cmat) = as.vector(data_wide$geneID)
```

```{r, message=FALSE, warning=TRUE}
tbl_markers_average = tbl_markers_average %>%
                       #  mutate(leiden_res_annot = factor(leiden_res_annot, levels = annot_order)) %>%
                       # mutate(leiden_res_annot = factor(leiden_res_annot, levels=c("Embryonic RG", "Juvenile RG", "Active NSCs", "Quiescent NSCs [1]", "Quiescent NSCs [2]"))) %>%
                        # mutate(geneID = factor(geneID, levels =rownames(cmat)[mat_cluster_rows$order]))
                        mutate(geneID = factor(geneID, levels=marker_list))


library("RColorBrewer")
```

```{r, fig.asp=2.2}
plt_cluster_marker_expr = ggplot(tbl_markers_average, aes(x=leiden_res_annot, y=geneID, fill=mean_expr)) +
                            geom_tile() +
                            scale_fill_distiller(palette = 'RdYlBu', breaks=c(0, 0.5, 1), limits=c(0,1)) +
                            theme_publication +
                            labs(x=NULL, y=NULL) +
                            scale_x_discrete(expand = c(0,0)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(fill="Expr (scaled)") +
                            theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
                            guides(fill = guide_colorbar(barwidth = 0.3,
                                                         barheight = 2))
                            # theme(axis.text.x=element_blank(),
                            #       axis.ticks.x=element_blank(),
                            #       axis.text.y=element_blank(),
                            #       axis.ticks.y=element_blank()) +
                            # labs(colour="Gate") +
                            # guides(colour = guide_legend(override.aes = list(size=2)))


plt_cluster_marker_expr_RGCs = plt_cluster_marker_expr
plt_cluster_marker_expr_RGCs
```



# AUCell KEGG Pathway Enrichment

```{r}
tbl_AUC = read_csv(paste0("data/AUC_pathways/AUC_pathways_KEGG_", fileID, ".csv.gz"))


library(reshape2)

tbl_AUC_long = tbl_AUC %>%
                      melt(id.vars = c("cellID"),
                          variable.name = "pathway",
                          value.name= "AUC_score") %>%
                      as_tibble()
                      

metadata_AUC = left_join(tbl_AUC_long, metadata %>% select(cellID, annot_leiden, UMAP_dim1, UMAP_dim2), by="cellID")
```


```{r}
metadata_mean_AUC = metadata_AUC %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score))
```

```{r}
plt_UMAP_AUC = ggplot(metadata_mean_AUC, aes(x=annot_leiden, y=pathway, fill=mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                               guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC score")
```

```{r}
plt_UMAP_AUC
```

```{r}
metadata_scaled_AUC = metadata_AUC %>%
                  group_by(pathway) %>%
                  mutate(norm_AUC_score = scale(AUC_score)) %>%
                  ungroup() %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score),
                            mean_norm_AUC_score = mean(norm_AUC_score)) %>%
                  group_by(pathway) %>%
                  mutate(norm_mean_AUC_score = scale(mean_AUC_score))                  
```

```{r}
# data_wide <- spread(olddata_long, condition, measurement)
tbl_scores = metadata_scaled_AUC %>%
            select(-c(mean_AUC_score, mean_norm_AUC_score)) %>%
            tidyr::spread(pathway, norm_mean_AUC_score)

cmat = as.matrix(tbl_scores %>% select(-annot_leiden))
rownames(cmat) = tbl_scores %>% pull(annot_leiden)

c <- cor(cmat, method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_cols <- hclust(d)

c <- cor(t(cmat), method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_rows <- hclust(d)

order_annot = rownames(cmat)[mat_cluster_rows$order]
order_pathways = colnames(cmat)[mat_cluster_cols$order]


metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=order_pathways)) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r}
plt_UMAP_AUC
```


## w/o gliogenic

```{r}
fileID_2 = "normal_subset_embryonic_RG_cleaned_wo_gliogenic"

tbl_AUC = read_csv(paste0("data/AUC_pathways/AUC_pathways_KEGG_", fileID_2, ".csv.gz"))


library(reshape2)

tbl_AUC_long = tbl_AUC %>%
                      melt(id.vars = c("cellID"),
                          variable.name = "pathway",
                          value.name= "AUC_score") %>%
                      as_tibble()
                      

metadata_AUC = left_join(tbl_AUC_long, metadata %>% select(cellID, annot_leiden, UMAP_dim1, UMAP_dim2), by="cellID")
```


```{r}
metadata_mean_AUC = metadata_AUC %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score))
```

```{r}
plt_UMAP_AUC = ggplot(metadata_mean_AUC, aes(x=annot_leiden, y=pathway, fill=mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                               guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC score")
```

```{r}
plt_UMAP_AUC
```

```{r}
metadata_scaled_AUC = metadata_AUC %>%
                  group_by(pathway) %>%
                  mutate(norm_AUC_score = scale(AUC_score)) %>%
                  ungroup() %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score),
                            mean_norm_AUC_score = mean(norm_AUC_score)) %>%
                  group_by(pathway) %>%
                  mutate(norm_mean_AUC_score = scale(mean_AUC_score))                  
```

```{r}
# data_wide <- spread(olddata_long, condition, measurement)
tbl_scores = metadata_scaled_AUC %>%
            select(-c(mean_AUC_score, mean_norm_AUC_score)) %>%
            tidyr::spread(pathway, norm_mean_AUC_score)

cmat = as.matrix(tbl_scores %>% select(-annot_leiden))
rownames(cmat) = tbl_scores %>% pull(annot_leiden)

c <- cor(cmat, method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_cols <- hclust(d)

c <- cor(t(cmat), method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_rows <- hclust(d)

order_annot = rownames(cmat)[mat_cluster_rows$order]
order_pathways = colnames(cmat)[mat_cluster_cols$order]


metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=order_pathways)) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r}
plt_UMAP_AUC
```




# AUCell Panther Pathway Enrichment

```{r}
tbl_AUC = read_csv(paste0("data/AUC_pathways/AUC_pathways_panther_", fileID, ".csv.gz"))


library(reshape2)

tbl_AUC_long = tbl_AUC %>%
                      melt(id.vars = c("cellID"),
                          variable.name = "pathway",
                          value.name= "AUC_score") %>%
                      as_tibble()
                      

metadata_AUC = left_join(tbl_AUC_long, metadata %>% select(cellID, annot_leiden, UMAP_dim1, UMAP_dim2), by="cellID")
```


```{r}
metadata_mean_AUC = metadata_AUC %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score))
```

```{r}
plt_UMAP_AUC = ggplot(metadata_mean_AUC, aes(x=annot_leiden, y=pathway, fill=mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                               guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC score")
```

```{r}
plt_UMAP_AUC
```

```{r}
metadata_scaled_AUC = metadata_AUC %>%
                  group_by(pathway) %>%
                  mutate(norm_AUC_score = scale(AUC_score)) %>%
                  ungroup() %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score),
                            mean_norm_AUC_score = mean(norm_AUC_score)) %>%
                  group_by(pathway) %>%
                  mutate(norm_mean_AUC_score = scale(mean_AUC_score))                  
```

```{r}
# data_wide <- spread(olddata_long, condition, measurement)
tbl_scores = metadata_scaled_AUC %>%
            select(-c(mean_AUC_score, mean_norm_AUC_score)) %>%
            tidyr::spread(pathway, norm_mean_AUC_score)

cmat = as.matrix(tbl_scores %>% select(-annot_leiden))
rownames(cmat) = tbl_scores %>% pull(annot_leiden)

c <- cor(cmat, method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_cols <- hclust(d)

c <- cor(t(cmat), method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_rows <- hclust(d)

order_annot = rownames(cmat)[mat_cluster_rows$order]
order_pathways = colnames(cmat)[mat_cluster_cols$order]


metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=order_pathways)) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r}
plt_UMAP_AUC
```





## w/o gliogenic


```{r}
tbl_AUC = read_csv(paste0("data/AUC_pathways/AUC_pathways_panther_", fileID_2, ".csv.gz"))


library(reshape2)

tbl_AUC_long = tbl_AUC %>%
                      melt(id.vars = c("cellID"),
                          variable.name = "pathway",
                          value.name= "AUC_score") %>%
                      as_tibble()
                      

metadata_AUC = left_join(tbl_AUC_long, metadata %>% select(cellID, annot_leiden, UMAP_dim1, UMAP_dim2), by="cellID")
```


```{r}
metadata_mean_AUC = metadata_AUC %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score))
```

```{r}
plt_UMAP_AUC = ggplot(metadata_mean_AUC, aes(x=annot_leiden, y=pathway, fill=mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                               guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC score")
```

```{r}
plt_UMAP_AUC
```

```{r}
metadata_scaled_AUC = metadata_AUC %>%
                  group_by(pathway) %>%
                  mutate(norm_AUC_score = scale(AUC_score)) %>%
                  ungroup() %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score),
                            mean_norm_AUC_score = mean(norm_AUC_score)) %>%
                  group_by(pathway) %>%
                  mutate(norm_mean_AUC_score = scale(mean_AUC_score))                  
```

```{r}
# data_wide <- spread(olddata_long, condition, measurement)
tbl_scores = metadata_scaled_AUC %>%
            select(-c(mean_AUC_score, mean_norm_AUC_score)) %>%
            tidyr::spread(pathway, norm_mean_AUC_score)

cmat = as.matrix(tbl_scores %>% select(-annot_leiden))
rownames(cmat) = tbl_scores %>% pull(annot_leiden)

c <- cor(cmat, method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_cols <- hclust(d)

c <- cor(t(cmat), method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_rows <- hclust(d)

order_annot = rownames(cmat)[mat_cluster_rows$order]
order_pathways = colnames(cmat)[mat_cluster_cols$order]


metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=order_pathways)) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r}
plt_UMAP_AUC
```


# SCENIC

```{r, message=FALSE, warning=FALSE}
source("code/core_functions_supp.R")

annot_order = c("Epithalamus",
                "Gliogenic (cortical)",
                "Ganglionic eminence",
                "Cortical pallium",
                "Thalamic eminence",
                "Gliogenic (ganglionic)",
                "Cortical hem",
                "Pretectum",
                "Subthalamic nucleus")



tbl_scenic_auc = read.csv(paste0("data/scenic/auc_mtx_", fileID, ".csv.gz"), row.names=1, check.names=FALSE)

tbl_scenic_auc_z_score = as_tibble(scale(tbl_scenic_auc), rownames="cellID")

tbl_scenic_rss_group = read_csv(paste0("data/scenic/rss_", fileID, "_", leiden_res, ".csv.gz")) %>%
                          rename(group = X1)




metadata_scenic = left_join(metadata %>% select(cellID, annot_leiden), as_tibble(tbl_scenic_auc, rownames="cellID"), by="cellID")

library(reshape2)

metadata_scenic_long = metadata_scenic %>%
                      melt(id.vars = c("cellID", "annot_leiden"),
                          variable.name = "pathway",
                          value.name= "AUC_score") %>%
                      as_tibble()






metadata = metadata %>%
              mutate(group_num = get(leiden_res)) %>%
              mutate(group = get(leiden_res_annot)) #%>%
              # mutate(group = factor(group, levels=annot_order))
```



```{r, message=FALSE, warning=TRUE, fig.asp=2}
# plt_scenic_top20 = plt_heatmap_scenic(tbl_scenic_auc_z_score, tbl_scenic_rss_group, metadata, n_genes = 20)
# plt_scenic_top20
```


```{r}
topreg = c()
n_genes = 20

num_order = metadata %>%
                select(group, group_num) %>%
                distinct() %>%
                arrange(group) %>%
                pull(group_num) %>%
                as.vector()

for (groupID in num_order){
  top_group = tbl_scenic_rss_group %>%
                  filter(group == groupID) %>%
                  melt(id.vars="group") %>%
                  as_tibble() %>%
                  arrange(desc(value)) %>%
                  head(n_genes) %>%
                  pull(variable) %>%
                  as.vector()
  topreg = c(topreg, top_group)
}


metadata_scenic_long = metadata_scenic_long %>%
                          filter(pathway %in% topreg)


metadata_mean_AUC = metadata_scenic_long %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score))
```

```{r}
plt_UMAP_AUC = ggplot(metadata_mean_AUC, aes(x=annot_leiden, y=pathway, fill=mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                               guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC score")
```

```{r, fig.asp=2}
plt_UMAP_AUC
```


```{r}
metadata_scaled_AUC = metadata_scenic_long %>%
                  group_by(pathway) %>%
                  mutate(norm_AUC_score = scale(AUC_score)) %>%
                  ungroup() %>%
                  group_by(pathway, annot_leiden) %>%
                  summarise(mean_AUC_score = mean(AUC_score),
                            mean_norm_AUC_score = mean(norm_AUC_score)) %>%
                  group_by(pathway) %>%
                  mutate(norm_mean_AUC_score = scale(mean_AUC_score))                  
```

```{r}
# data_wide <- spread(olddata_long, condition, measurement)
tbl_scores = metadata_scaled_AUC %>%
            select(-c(mean_AUC_score, mean_norm_AUC_score)) %>%
            tidyr::spread(pathway, norm_mean_AUC_score)

cmat = as.matrix(tbl_scores %>% select(-annot_leiden))
rownames(cmat) = tbl_scores %>% pull(annot_leiden)

c <- cor(cmat, method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_cols <- hclust(d)

c <- cor(t(cmat), method="spearman")
d <- as.dist(1-c)  # because correlation is a similarity measure and
mat_cluster_rows <- hclust(d)

order_annot = rownames(cmat)[mat_cluster_rows$order]
order_pathways = colnames(cmat)[mat_cluster_cols$order]


metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=order_pathways)) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r, fig.asp=2}
plt_UMAP_AUC
```


```{r}
metadata_scaled_AUC = metadata_scaled_AUC %>%
                mutate(pathway = factor(pathway, levels=unique(topreg))) %>%
                mutate(annot_leiden = factor(annot_leiden, levels=order_annot))
```


```{r}
plt_UMAP_AUC = ggplot(metadata_scaled_AUC, aes(x=annot_leiden, y=pathway, fill=norm_mean_AUC_score)) +
                            geom_tile() +
                            scale_colour_viridis() +
                            scale_fill_viridis() +
                            theme_publication +
                            scale_x_discrete(expand = c(0,0),
                                             guide = guide_axis(angle=45)) +
                            scale_y_discrete(expand = c(0,0)) +
                            labs(x=NULL, y=NULL) +
                            labs(fill="AUC z-score mean")
```

```{r, fig.asp=2}
plt_UMAP_AUC
```



