---
title: "NSCs - Kalamakis 2019"
author: "Daniel J. Kunz"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: zenburn
    code_folding: hide
editor_options:
  chunk_output_type: console
---



```{r setup, message=FALSE, warning=TRUE}
library(ggplot2)
library(viridis)
library(patchwork)

library(readr)
library(dplyr)
library(tibble)
```



```{r, message=FALSE, warning=TRUE}
source("code/core_settings.R")
source("code/core_functions.R")
```


```{r}
# # on openstack
# library(readr)
# library(dplyr)
# library(tibble)
# 
# library(reticulate)
# use_python("/usr/bin/python3")
# 
# # set parameters
# 
# adata_path = paste0('data/forebrain_normal_subset_neuronal_glial_cleaned_Kalamakis_integration_harmony.h5ad')
# 
# 
# py_run_string("import numpy as np")
# py_run_string("import anndata as ad")
# 
# py_run_string("adata = ad.read_h5ad(r.adata_path)")
# 
# 
# metadata_scanpy = as_tibble(py$adata$obs, rownames="cellID") %>%
#                     select(-74) %>%
#                     rename(mt_frac = percent_mito) %>%
#                     mutate(UMAP_dim1 = py$adata$obsm[['X_umap']][,1],
#                            UMAP_dim2 = py$adata$obsm[['X_umap']][,2])
# 
# write_csv(metadata_scanpy, "data/metadata/metadata_forebrain_normal_subset_neuronal_glial_cleaned_Kalamakis_integration_harmony.csv.gz")
```



```{r}
metadata = read_csv("data/metadata/metadata_forebrain_normal_subset_neuronal_glial_cleaned_Kalamakis_integration_harmony.csv.gz",
col_types = "cccccccccddddccccccccccccccccccccdddccccccccccccccccccccccccccccccccccccdcccccdddddddddccdd")

metadata = metadata %>%
              mutate(annot_leiden = if_else(annot_leiden == "nan", NA_character_, annot_leiden)) %>%
              mutate(annot_kalamakis = if_else(annot_kalamakis == "nan", NA_character_, annot_kalamakis))
              
celltype_colours = neuronal_glial_colours
colour_celltypes = neuronal_glial_colours
annot_order = names(neuronal_glial_colours)
```

# Cluster annotation


```{r}
library(ggrepel)
library(ggthemes)
library(ggrastr)

plot_UMAP_leiden <- function(leiden_key){
  
  metadata = metadata %>%
              mutate(leiden = get(leiden_key))
              
  cl_cent = metadata %>%
                  select(UMAP_dim1, UMAP_dim2, leiden) %>%
                  group_by(leiden) %>%
                  summarize_all(mean)
  
  # randomise order for plot
  plt_UMAP_leiden = ggplot(slice(metadata, sample(1:n())) %>% arrange(!is.na(leiden)), aes(x=UMAP_dim1, y=UMAP_dim2, colour=leiden)) +
                              # geom_point(size=0.5, alpha=0.8, shape=16) +
                              # geom_point_rast(size=0.2, alpha=0.8, shape=16, raster.dpi=300) +
                              # geom_point_rast(size=0.5, , alpha=0.8, shape=16, raster.dpi=600) +
                              geom_point_rast(size=0.4, stroke=0, alpha=0.8, shape=16, raster.dpi=600) +
                              geom_label_repel(aes(x=UMAP_dim1, y=UMAP_dim2, label=leiden),
                                      fill='white', colour='black', label.size=NA,
                                      alpha=0.9, label.padding = 0.1, point.padding = 0,
                                      data=cl_cent, size=1.78, show.legend=FALSE, inherit.aes=F) +
                              scale_colour_manual(values=celltype_colours, na.value="lightgrey") +
                              theme_publication +
                              labs(x="UMAP 1", y="UMAP 2") +
                              theme(axis.text.x=element_blank(),
                                    axis.ticks.x=element_blank(),
                                    axis.text.y=element_blank(),
                                    axis.ticks.y=element_blank()) +
                              # guides(color = guide_legend(override.aes = list(size=3))) +
                              # labs(colour="Leiden")
                              # labs(title=paste0(leiden_key)) +
                              theme(legend.position="none")

  return(plt_UMAP_leiden)
}
```

```{r}
plt_UMAP_neuronal_glial = plot_UMAP_leiden("annot_leiden")
plt_UMAP_neuronal_glial
```





```{r}
celltype_colours = c("Embryonic RG" = "#C72228",
                          "Juvenile RG & TAPs" = "#FF891C",
                          "Gliogenic precursors (aNSCs)" = "#FACB12",
                          "Gliogenic precursors (APCs)" = "#F9DECF",
                          "Ependymal cells" = "#139992",
                          "Quiescent NSCs [1]" = "#DABE99",
                          "Quiescent NSCs (dorsal)" = "#DABE99",
                          "Quiescent NSCs [2]" = "#635547",
                          "Quiescent NSCs (ventral)" = "#635547",
                          "Early EmNBs [1]" = "#005579",
                          "Early EmNBs [2]" = "#8DB5CE",
                          "GABAergic INs" = "#CDE088",
                          "GE NBs [1]" = "#3F84AA",
                          "GE NBs [2]" = "#F7F79E",
                          "ImStNeurons" = "#B51D8D",
                          "Hippocampal NBs [1]" = "#C594BF",
                          "Hippocampal NBs [2]" = "#F397C0",
                          "ImPreMDs" = "#CC7818",
                          "PreM-ODCs" = "#CC7818",
                          "Oligodendrocytes [1]" = "#8870AD",
                          "Oligodendrocytes [2]" = "#532C8A",
                          
                          "TAP" = "#FF891C",
                          "qNSC [1]" = "#DABE99",
                          "qNSC [2]" = "#635547",
                          "aNSC [1]" = "#FACB12",
                          "aNSC [2]" = "#F9DECF",

                          "TBD [TAP/aNSC] [3]" = "#C594BF",

                          "TBD [1]" = "#005579",
                          "TBD [2]" = "#8DB5CE",

                          "NB" = "#B51D8D",
                          "OPCs" = "#139992",
                          "Oligodendrocytes" = "#532C8A"
                        )



# celltype_colours = 
plt_UMAP_kalamakis = plot_UMAP_leiden("annot_kalamakis") +
                        guides(colour = guide_legend(override.aes = list(alpha=1, size=2),
                                                     keyheight=0.3,
                                                     default.unit="cm")) +
                        labs(colour="Kalamakis 2019") +
                         theme(legend.position="right")

plt_UMAP_kalamakis
```



```{r}
library(ggrepel)
library(ggthemes)
library(ggrastr)

plot_UMAP_leiden <- function(leiden_key){
  
  metadata = metadata %>%
              mutate(leiden = get(leiden_key))
              
  cl_cent = metadata %>%
                  select(UMAP_dim1, UMAP_dim2, leiden) %>%
                  group_by(leiden) %>%
                  summarize_all(mean)
  
  # randomise order for plot
  plt_UMAP_leiden = ggplot(slice(metadata, sample(1:n())), aes(x=UMAP_dim1, y=UMAP_dim2, colour=leiden)) +
                              # geom_point(size=0.5, alpha=0.8, shape=16) +
                              geom_point_rast(size=0.4, stroke=0, alpha=0.8, shape=16, raster.dpi=600) +
                              # geom_point_rast(size=0.2, alpha=0.8, shape=16, raster.dpi=300) +
                              # geom_point_rast(size=0.2, alpha=0.8, shape=16, raster.dpi=600) +
                              geom_label_repel(aes(x=UMAP_dim1, y=UMAP_dim2, label=leiden),
                                      fill='white', colour='black', label.size=NA,
                                      alpha=0.9, label.padding = 0.1, point.padding = 0,
                                      data=cl_cent, size=1.78, show.legend=FALSE, inherit.aes=F) +
                              scale_colour_manual(values=celltype_colours, na.value="grey") +
                              theme_publication +
                              labs(x="UMAP 1", y="UMAP 2") +
                              theme(axis.text.x=element_blank(),
                                    axis.ticks.x=element_blank(),
                                    axis.text.y=element_blank(),
                                    axis.ticks.y=element_blank()) +
                              guides(colour = guide_legend(override.aes = list(alpha=1, size=2),
                                                           keyheight=0.3,
                                                           default.unit="cm")) +
                              # guides(color = guide_legend(override.aes = list(size=3))) +
                              labs(colour="Kalamakis 2019")
                              # labs(title=paste0(leiden_key)) +
                              # theme(legend.position="none")

  return(plt_UMAP_leiden)
}
```




```{r}
metadata = metadata %>% filter(!is.na(annot_kalamakis))

plt_UMAP_kalamakis_only = plot_UMAP_leiden("annot_kalamakis")
plt_UMAP_kalamakis_only
```

```{r}
plt_panel = (plt_UMAP_neuronal_glial + labs(title="Neuronal & glial subset") + theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit="mm"))) +
            (plt_UMAP_kalamakis + labs(title="Kalamakis 2019") + theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit="mm")))

plt_panel

# ggsave("figures/figure_Kalamakis_2019/UMAP_panel_integration_neuronal_glial_Kalamakis_2019.pdf", plot=plt_panel + theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit="mm"), legend.margin=margin(0, 0, 0, -2, unit='mm')), height=7, width=18.3, units="cm")
# ggsave("figures/figure_Kalamakis_2019/UMAP_panel_integration_neuronal_glial_Kalamakis_2019.pdf", plot=plt_panel + theme(plot.margin = margin(0, 0, 0, 0, unit="mm"), legend.margin=margin(0, 0, 0, -2, unit='mm')), height=7, width=18.3, units="cm")

ggsave("figures/figure_Kalamakis_2019/UMAP_panel_integration_neuronal_glial_Kalamakis_2019.pdf", plot=plt_panel + theme(legend.margin=margin(0, 0, 0, -2, unit='mm')), height=7, width=18.3, units="cm")

```